regenerated *.in after updating configure.ac, lib/Makefile.am and src/Makefile.am

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION EXEEXT OBJEXT ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh INSTALL_STRIP_PROGRAM AWK SET_MAKE AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH DEPDIR CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX am__include am__quote CXXDEPMODE RANLIB ac_ct_RANLIB regex_cmd gencat_cmd CXXCPP EGREP SHAPE MITSHM DEBUG NLS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION EXEEXT OBJEXT ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh INSTALL_STRIP_PROGRAM AWK SET_MAKE AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH DEPDIR CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX am__include am__quote CXXDEPMODE RANLIB ac_ct_RANLIB regex_cmd gencat_cmd CXXCPP EGREP SHAPE MITSHM xftconfig XFT DEBUG NLS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -857,6 +857,8 @@ Optional Features:
   --enable-shape          enable support of the SHAPE extension
                           [default=yes]
   --enable-mitshm         enable support of the MIT-SHM extension
+                          [default=yes]
+  --enable-xft            enable support for the Xft library
                           [default=yes]
   --enable-debug          include verbose debugging code [default=no]
   --enable-nls            include natural language support [default=yes]
@@ -4561,6 +4563,200 @@ else
 fi
 
 
+echo "$as_me:$LINENO: checking whether to build support for Xft" >&5
+echo $ECHO_N "checking whether to build support for Xft... $ECHO_C" >&6
+# Check whether --enable-xft or --disable-xft was given.
+if test "${enable_xft+set}" = set; then
+  enableval="$enable_xft"
+  XFT="$enableval"
+else
+  XFT=yes
+fi;
+echo "$as_me:$LINENO: result: $XFT" >&5
+echo "${ECHO_T}$XFT" >&6
+
+if test "x$XFT" = "xyes"; then
+  # Check for freetype-config and get the CXXFLAGS and LIBS from it
+  for ac_prog in xft-config
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_xftconfig+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$xftconfig"; then
+  ac_cv_prog_xftconfig="$xftconfig" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_xftconfig="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+xftconfig=$ac_cv_prog_xftconfig
+if test -n "$xftconfig"; then
+  echo "$as_me:$LINENO: result: $xftconfig" >&5
+echo "${ECHO_T}$xftconfig" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$xftconfig" && break
+done
+
+  if test "x$xftconfig" != "x"; then
+    save_CXXFLAGS="$CXXFLAGS"
+    save_LIBS="$LIBS"
+
+    CXXFLAGS="$CXXFLAGS `xft-config --cflags`"
+    LIBS="`xft-config --libs` $LIBS"
+
+    echo "$as_me:$LINENO: checking for XftGlyphExtents in -lXft" >&5
+echo $ECHO_N "checking for XftGlyphExtents in -lXft... $ECHO_C" >&6
+if test "${ac_cv_lib_Xft_XftGlyphExtents+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lXft  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char XftGlyphExtents ();
+int
+main ()
+{
+XftGlyphExtents ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Xft_XftGlyphExtents=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_Xft_XftGlyphExtents=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_Xft_XftGlyphExtents" >&5
+echo "${ECHO_T}$ac_cv_lib_Xft_XftGlyphExtents" >&6
+if test $ac_cv_lib_Xft_XftGlyphExtents = yes; then
+  XFT=yes
+else
+  XFT=no
+fi
+
+
+for ac_header in X11/Xft/Xft.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#define _XFT_NO_COMPAT
+#include <X11/Xlib.h>
+
+
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_Header=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_Header=no"
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ XFT=yes
+else
+  XFT=no
+fi
+
+done
+
+
+    if test "x$XFT" = "xyes"; then
+      XFT="-DXFT -D_XFT_NO_COMPAT"
+    else
+      XFT=
+      CXXFLAGS="$save_CXXFLAGS"
+      LIBS="$save_LIBS"
+    fi
+  else
+    XFT=
+  fi
+else
+  XFT=
+fi
+
+
 echo "$as_me:$LINENO: checking whether to include verbose debugging code" >&5
 echo $ECHO_N "checking whether to include verbose debugging code... $ECHO_C" >&6
 # Check whether --enable-debug or --disable-debug was given.
@@ -5327,6 +5523,8 @@ s,@CXXCPP@,$CXXCPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@SHAPE@,$SHAPE,;t t
 s,@MITSHM@,$MITSHM,;t t
+s,@xftconfig@,$xftconfig,;t t
+s,@XFT@,$XFT,;t t
 s,@DEBUG@,$DEBUG,;t t
 s,@NLS@,$NLS,;t t
 s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
