remove configure checks for TIMEDCACHE
add configure checks for MIT-SHM extension

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -847,9 +847,10 @@ Optional Features:
   --enable-dependency-tracking  Do not reject slow dependency extractors
   --enable-shape          enable support of the XShape extension
                           [default=yes]
+  --enable-mitshm         enable support of the MIT-SHM extension
+                          [default=yes]
   --enable-debug          include verbose debugging code [default=no]
   --enable-nls            include natural language support [default=yes]
-  --enable-timed-cache    use new timed pixmap cache [default=yes]
   --enable-maintainer-mode enable make rules and dependencies not useful
                           (and sometimes confusing) to the casual installer
 
@@ -4295,9 +4296,9 @@ echo "$as_me: error: Could not find XOpenDisplay in -lX11" >&2;}
 fi
 
 
-Xext_lib=""
+Xext_lib=
 
-SHAPE=""
+SHAPE=
 echo "$as_me:$LINENO: checking whether to build support for the XShape extension" >&5
 echo $ECHO_N "checking whether to build support for the XShape extension... $ECHO_C" >&6
 # Check whether --enable-shape or --disable-shape was given.
@@ -4428,7 +4429,141 @@ fi
 
 LIBS="$LIBS $Xext_lib"
 
-DEBUG=""
+MITSHM=
+echo "$as_me:$LINENO: checking whether to build support for the MIT-SHM extension" >&5
+echo $ECHO_N "checking whether to build support for the MIT-SHM extension... $ECHO_C" >&6
+# Check whether --enable-mitshm or --disable-mitshm was given.
+if test "${enable_mitshm+set}" = set; then
+  enableval="$enable_mitshm"
+
+fi;
+
+: ${enableval="yes"}
+if test x$enableval = "xyes"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  echo "$as_me:$LINENO: checking for XShmPutImage in -lXext" >&5
+echo $ECHO_N "checking for XShmPutImage in -lXext... $ECHO_C" >&6
+if test "${ac_cv_lib_Xext_XShmPutImage+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lXext  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char XShmPutImage ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+XShmPutImage ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Xext_XShmPutImage=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_Xext_XShmPutImage=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_Xext_XShmPutImage" >&5
+echo "${ECHO_T}$ac_cv_lib_Xext_XShmPutImage" >&6
+if test $ac_cv_lib_Xext_XShmPutImage = yes; then
+  echo "$as_me:$LINENO: checking for X11/extensions/XShm.h" >&5
+echo $ECHO_N "checking for X11/extensions/XShm.h... $ECHO_C" >&6
+                cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <X11/Xlib.h>
+#include <X11/Xutil.h>
+#include <sys/types.h>
+#include <sys/ipc.h>
+#include <sys/shm.h>
+#include <X11/extensions/XShm.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+ long foo = ShmCompletion
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+                echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+                MITSHM="-DMITSHM"; Xext_lib="-lXext"
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+fi
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+LIBS=`echo "$LIBS $Xext_lib" | sed -e 's/-lXext -lXext/-lXext/'`
+
+DEBUG=
 echo "$as_me:$LINENO: checking whether to include verbose debugging code" >&5
 echo $ECHO_N "checking whether to include verbose debugging code... $ECHO_C" >&6
 # Check whether --enable-debug or --disable-debug was given.
@@ -4450,7 +4585,7 @@ echo "${ECHO_T}no" >&6
 fi;
 
 
-NLS=""
+NLS=
 echo "$as_me:$LINENO: checking whether to include NLS support" >&5
 echo $ECHO_N "checking whether to include NLS support... $ECHO_C" >&6
 # Check whether --enable-nls or --disable-nls was given.
@@ -4575,33 +4710,8 @@ fi
 done
 
 if test x$gencat_cmd = "x"; then
-  NLS=""
+  NLS=
 fi
-
-
-TIMEDCACHE=""
-echo "$as_me:$LINENO: checking whether to use the new timed pixmap cache" >&5
-echo $ECHO_N "checking whether to use the new timed pixmap cache... $ECHO_C" >&6
-# Check whether --enable-timed-cache or --disable-timed-cache was given.
-if test "${enable_timed_cache+set}" = set; then
-  enableval="$enable_timed_cache"
-
-  if test x$enableval = "xyes"; then
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-    TIMEDCACHE="-DTIMEDCACHE"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-  fi
-else
-
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-  TIMEDCACHE="-DTIMEDCACHE"
-
-fi;
-
 
 echo "$as_me:$LINENO: checking whether to enable maintainer-specific portions of Makefiles" >&5
 echo $ECHO_N "checking whether to enable maintainer-specific portions of Makefiles... $ECHO_C" >&6
@@ -5293,10 +5403,10 @@ s,@ac_ct_CC@,$ac_ct_CC,;t t
 s,@CCDEPMODE@,$CCDEPMODE,;t t
 s,@CPP@,$CPP,;t t
 s,@SHAPE@,$SHAPE,;t t
+s,@MITSHM@,$MITSHM,;t t
 s,@DEBUG@,$DEBUG,;t t
 s,@NLS@,$NLS,;t t
 s,@gencat_cmd@,$gencat_cmd,;t t
-s,@TIMEDCACHE@,$TIMEDCACHE,;t t
 s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
 s,@MAINTAINER_MODE_FALSE@,$MAINTAINER_MODE_FALSE,;t t
 s,@MAINT@,$MAINT,;t t
